services:
  # Backend Flask
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: multi-domain-dashboard-backend-prod
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - MULTI_DOMAIN_MODE=true
      - DOMAINS_CONFIG_PATH=/app/domains.json
      # Legacy environment variables for backward compatibility
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID:-1vPoodpppoT0CF0ly7RSaEGjYzaHvWchYiimNPcUyHTI}
      - CLIENT_NAME=${CLIENT_NAME:-Desktop}
    volumes:
      - ./data:/app/data
      - ./backend/domains.json:/app/domains.json
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "python3", "/app/docker-healthcheck.py"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 40s

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: multi-domain-dashboard-frontend-prod
    environment:
      - REACT_APP_MULTI_DOMAIN=true
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://backend:5000}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Nginx Proxy Reverso
  nginx:
    image: nginx:alpine
    container_name: multi-domain-dashboard-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./frontend/build:/var/www/html:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  dashboard-network:
    driver: bridge

volumes:
  data:
    driver: local
